# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\x12\x08glossary\x1a\x1bgoogle/protobuf/empty.proto\",\n\x04Term\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\x11\n\x0fGetTermsRequest\"1\n\x10GetTermsResponse\x12\x1d\n\x05terms\x18\x01 \x03(\x0b\x32\x0e.glossary.Term\"!\n\x0eGetTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"6\n\x0e\x41\x64\x64TermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"9\n\x11UpdateTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"$\n\x11\x44\x65leteTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t2\xbc\x02\n\x0fGlossaryService\x12\x41\n\x08GetTerms\x12\x19.glossary.GetTermsRequest\x1a\x1a.glossary.GetTermsResponse\x12\x33\n\x07GetTerm\x12\x18.glossary.GetTermRequest\x1a\x0e.glossary.Term\x12\x33\n\x07\x41\x64\x64Term\x12\x18.glossary.AddTermRequest\x1a\x0e.glossary.Term\x12\x39\n\nUpdateTerm\x12\x1b.glossary.UpdateTermRequest\x1a\x0e.glossary.Term\x12\x41\n\nDeleteTerm\x12\x1b.glossary.DeleteTermRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TERM']._serialized_start=57
  _globals['_TERM']._serialized_end=101
  _globals['_GETTERMSREQUEST']._serialized_start=103
  _globals['_GETTERMSREQUEST']._serialized_end=120
  _globals['_GETTERMSRESPONSE']._serialized_start=122
  _globals['_GETTERMSRESPONSE']._serialized_end=171
  _globals['_GETTERMREQUEST']._serialized_start=173
  _globals['_GETTERMREQUEST']._serialized_end=206
  _globals['_ADDTERMREQUEST']._serialized_start=208
  _globals['_ADDTERMREQUEST']._serialized_end=262
  _globals['_UPDATETERMREQUEST']._serialized_start=264
  _globals['_UPDATETERMREQUEST']._serialized_end=321
  _globals['_DELETETERMREQUEST']._serialized_start=323
  _globals['_DELETETERMREQUEST']._serialized_end=359
  _globals['_GLOSSARYSERVICE']._serialized_start=362
  _globals['_GLOSSARYSERVICE']._serialized_end=678
# @@protoc_insertion_point(module_scope)
